name: Build Lune AppImage

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:    
    name: Build the AppImage 
    runs-on: ubuntu-latest

    steps:
      - name: Runner info
        run: uname -ar
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: AppImage routine
        run: |
          export LUNE_VERSION=${{ vars.lune_VERSION }}
        
          echo "Running build on debian linux $(uname -m)"

          sudo apt-get update
          sudo apt-get install imagemagick file desktop-file-utils curl wget dpkg-dev unzip fuse libfuse2 -y
          
          wget "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod a+x ./appimagetool-x86_64.AppImage
          
          ./appimagetool-x86_64.AppImage ./package/appimage/lune.AppDir
          
          mkdir ../out
          mv ./lune-*.AppImage ../out/lune-$LUNE_VERSION.glibc${{ vars.LUNE_GLIBC_VERSION }}-x86_64.AppImage

      - name: Upload generated images
        uses: actions/upload-artifact@v4
        with:
          name: lune-${{ vars.lune_VERSION }}.glibc${{ vars.LUNE_GLIBC_VERSION }}-x86_64.AppImage
          path: "*.AppImage"
          if-no-files-found: error
