name: Build Lune AppImage

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:    
    name: Build the AppImage 
    runs-on: ubuntu-latest

    steps:
      - name: Runner info
        run: uname -ar
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: AppImage routine
        run: |
          export LUNE_VERSION=${{ vars.LUNE_VERSION }}

          sudo apt-get update
          sudo apt-get install imagemagick file desktop-file-utils curl wget dpkg-dev unzip fuse libfuse2 -y
          
          cd ./package/appimage
          ./pkg2appimage/pkg2appimage lune.yml

      - name: Upload generated images
        uses: actions/upload-artifact@v4
        with:
          name: lune-${{ vars.LUNE_VERSION }}-x86_64.AppImage
          path: ./package/appimage/out/*.AppImage
          if-no-files-found: error
