name: Build Lune AppImage

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:    
    name: Build the AppImage 
    runs-on: ubuntu-latest

    steps:
      - name: Runner info
        run: uname -ar
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: AppImage routine
        run: |
          export LUNE_VERSION=${{ vars.lune_VERSION }}
        
          echo "Running build on debian linux $(uname -m)"

          apt update
          apt install imagemagick file desktop-file-utils curl wget dpkg-dev unzip fuse libfuse2 -y
          
          wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-$(uname -m).AppImage -O /usr/bin/appimagetool
          chmod a+x /usr/bin/appimagetool
          
          cd /build/lune.AppDir
          ARCH=$(uname -m) /usr/bin/appimagetool .
          
          mkdir ../out
          mv ./lune-*.AppImage  ../out/lune-$LUNE_VERSION.glibc2.34-$(uname -m).AppImage

      - name: Upload generated images
        uses: actions/upload-artifact@v4
        with:
          name: lune-0.7.7.glibc2.34-${{ vars.LUNE_VERSION }}.AppImage
          path: ./package/appimage/out/lune-${{ vars.LUNE_VERSION }}.glibc2.34-${{ matrix.arch }}.AppImage
